### ISSUE TITLE
Traits example

### ISSUE THREAD

**Issue by mindplay-dk** [mindplay-dk/php-generics-rfc#15]
Review the last example in the "Traits" section.

Is it a good example?

Do we need it?

(earlier sections of the RFC already stated that type parameters may be referenced in type declarations.)

**Comment by morrisonlevi** [comment]
> Is it a good example?

No. It wouldn't work because there would be a conflict on the `make` method which is still present; using `as` in this case creates an alias, it does not rename.

I will replace it with an example of a trait that fulfills all the requirements of the `OuterIterator` interface and show it being used to implement some other sort of iterator decorator.

**Comment by mindplay-dk** [comment]
@orolyn points out this part of the example is invalid:

https://github.com/mindplay-dk/php-generics-rfc/blob/master/generics.txt#L235

We can't know the constructor arguments required by the template type `D`.

**Comment by morrisonlevi** [comment]
Example updated in [cc7219792a5b35226129d09536789afe20eac029](https://github.com/mindplay-dk/php-generics-rfc/commit/cc7219792a5b35226129d09536789afe20eac029)
